plugins {
	id 'java-library'
}

dependencies {
	implementation project(':common')

	compileOnly 'org.springframework.modulith:spring-modulith-api'
	compileOnly 'org.springframework:spring-context'
	compileOnly 'org.springframework:spring-tx'

	testImplementation 'org.junit.jupiter:junit-jupiter'
	testImplementation 'org.springframework:spring-tx'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
