plugins {
	id 'java-library'
}

dependencies {
	implementation project(':application')
	implementation project(':common')

	compileOnly 'org.springframework:spring-context'

	testImplementation 'org.junit.jupiter:junit-jupiter'
	testImplementation 'org.assertj:assertj-core'
	testImplementation 'org.springframework:spring-context'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
