plugins {
	id 'org.springframework.boot'
}

dependencies {
	implementation project(':api')
	implementation project(':domain')
	implementation project(':adapter')
	implementation project(':common')

	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.modulith:spring-modulith-starter-core'

	runtimeOnly 'org.postgresql:postgresql'
	runtimeOnly 'org.springframework.modulith:spring-modulith-actuator'
	runtimeOnly 'org.springframework.modulith:spring-modulith-observability'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.modulith:spring-modulith-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
