plugins {
	id 'java-library'
}

dependencies {
	implementation project(':application')
	implementation project(':common')
	implementation project(':logging')

	compileOnly 'org.springframework.modulith:spring-modulith-api'

	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.security:spring-security-core'
	implementation 'org.springframework.security:spring-security-oauth2-jose'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.16'

	compileOnly 'org.springframework.modulith:spring-modulith-api'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-web'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
