-- Nearby JPA 엔티티의 초기 PostgreSQL 스키마를 생성한다.
create table user_account (
    id bigint generated by default as identity primary key,
    role varchar(255) not null,
    status varchar(255) not null,
    phone_number varchar(255),
    phone_verified_at timestamp,
    onboarding_status varchar(255) not null,
    created_at timestamp not null,
    deleted_at timestamp
);

create table term (
    id bigint generated by default as identity primary key,
    term_key varchar(255) not null,
    version varchar(255) not null,
    required boolean not null
);

create table place_cache (
    id bigint generated by default as identity primary key,
    google_place_id varchar(255) not null,
    name varchar(255) not null,
    address varchar(255),
    latitude numeric(11, 8) not null,
    longitude numeric(11, 8) not null,
    category varchar(255),
    phone_number varchar(255),
    rating numeric(38, 2),
    review_count integer,
    photo_reference varchar(255),
    business_status varchar(255) not null
);

create table social_account (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    provider varchar(255) not null,
    provider_user_id varchar(255) not null,
    constraint fk_social_account_user foreign key (user_id) references user_account (id)
);

create table refresh_token (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token_hash varchar(255) not null,
    expires_at timestamp not null,
    revoked_at timestamp,
    constraint fk_refresh_token_user foreign key (user_id) references user_account (id)
);

create table phone_verification (
    id bigint generated by default as identity primary key,
    user_id bigint,
    phone_number varchar(255) not null,
    carrier varchar(255),
    status varchar(255) not null,
    expires_at timestamp not null,
    verified_at timestamp,
    constraint fk_phone_verification_user foreign key (user_id) references user_account (id)
);

create table emergency_contact (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    name varchar(255) not null,
    phone_number varchar(255) not null,
    constraint fk_emergency_contact_user foreign key (user_id) references user_account (id)
);

create table user_term_agreement (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    term_id bigint not null,
    agreed_at timestamp not null,
    constraint fk_user_term_agreement_user foreign key (user_id) references user_account (id),
    constraint fk_user_term_agreement_term foreign key (term_id) references term (id)
);

create table solo_dining_favorite (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    place_id bigint not null,
    created_at timestamp not null,
    constraint fk_solo_dining_favorite_place foreign key (place_id) references place_cache (id)
);

create table companion_profile (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    nickname varchar(255) not null,
    gender varchar(255) not null,
    birth_year integer,
    profile_image_url varchar(255),
    intro varchar(255),
    manner_score numeric(3, 2) not null,
    review_count integer not null,
    status varchar(255) not null
);

create table companion_profile_style (
    profile_id bigint not null,
    keyword varchar(255) not null,
    primary key (profile_id, keyword),
    constraint fk_companion_profile_style_profile foreign key (profile_id) references companion_profile (id)
);

create table companion_post (
    id bigint generated by default as identity primary key,
    host_user_id bigint not null,
    place_id bigint not null,
    meeting_at timestamp not null,
    max_participants integer not null,
    content text not null,
    open_chat_url varchar(255) not null,
    status varchar(255) not null,
    created_at timestamp not null
);

create table companion_post_style (
    post_id bigint not null,
    keyword varchar(255) not null,
    primary key (post_id, keyword),
    constraint fk_companion_post_style_post foreign key (post_id) references companion_post (id)
);

create table companion_application (
    id bigint generated by default as identity primary key,
    post_id bigint not null,
    applicant_user_id bigint not null,
    status varchar(255) not null,
    rejection_reason text,
    created_at timestamp not null,
    constraint fk_companion_application_post foreign key (post_id) references companion_post (id)
);

create table companion_match (
    id bigint generated by default as identity primary key,
    post_id bigint not null,
    status varchar(255) not null,
    created_at timestamp not null,
    constraint fk_companion_match_post foreign key (post_id) references companion_post (id)
);

create table companion_match_participant (
    id bigint generated by default as identity primary key,
    match_id bigint not null,
    user_id bigint not null,
    accepted_application_id bigint,
    role varchar(255) not null,
    constraint fk_companion_match_participant_match foreign key (match_id) references companion_match (id),
    constraint fk_companion_match_participant_application foreign key (accepted_application_id) references companion_application (id)
);

create table companion_schedule (
    id bigint generated by default as identity primary key,
    match_id bigint not null,
    place_id bigint not null,
    scheduled_at timestamp not null,
    estimated_duration_minutes integer,
    confirmed boolean not null,
    constraint fk_companion_schedule_match foreign key (match_id) references companion_match (id)
);

create table companion_meeting (
    id bigint generated by default as identity primary key,
    match_id bigint not null,
    status varchar(255) not null,
    started_at timestamp,
    completed_at timestamp,
    constraint fk_companion_meeting_match foreign key (match_id) references companion_match (id)
);

create table meeting_check_in (
    id bigint generated by default as identity primary key,
    meeting_id bigint not null,
    user_id bigint not null,
    latitude numeric(11, 8) not null,
    longitude numeric(11, 8) not null,
    checked_in_at timestamp not null,
    constraint fk_meeting_check_in_meeting foreign key (meeting_id) references companion_meeting (id)
);

create table meeting_cancellation (
    id bigint generated by default as identity primary key,
    meeting_id bigint not null,
    canceled_by_user_id bigint not null,
    reason text not null,
    canceled_at timestamp not null,
    constraint fk_meeting_cancellation_meeting foreign key (meeting_id) references companion_meeting (id)
);

create table companion_report (
    id bigint generated by default as identity primary key,
    meeting_id bigint not null,
    reporter_user_id bigint not null,
    reported_user_id bigint not null,
    detail text,
    created_at timestamp not null,
    constraint fk_companion_report_meeting foreign key (meeting_id) references companion_meeting (id),
    constraint uk_companion_report_meeting_reporter_reported unique (meeting_id, reporter_user_id, reported_user_id)
);

create table companion_report_reason (
    report_id bigint not null,
    reason varchar(255) not null,
    primary key (report_id, reason),
    constraint fk_companion_report_reason_report foreign key (report_id) references companion_report (id)
);

create table companion_review (
    id bigint generated by default as identity primary key,
    meeting_id bigint not null,
    reviewer_user_id bigint not null,
    reviewee_user_id bigint not null,
    rating integer not null,
    created_at timestamp not null,
    constraint fk_companion_review_meeting foreign key (meeting_id) references companion_meeting (id)
);

create table companion_review_keyword (
    review_id bigint not null,
    keyword varchar(255) not null,
    primary key (review_id, keyword),
    constraint fk_companion_review_keyword_review foreign key (review_id) references companion_review (id)
);

create table event_publication (
    id uuid primary key,
    publication_date timestamp(6) with time zone not null,
    listener_id varchar(255) not null,
    serialized_event varchar(255) not null,
    event_type varchar(255) not null,
    completion_date timestamp(6) with time zone
);

create table event_publication_archive (
    id uuid primary key,
    publication_date timestamp(6) with time zone not null,
    listener_id varchar(255) not null,
    serialized_event varchar(255) not null,
    event_type varchar(255) not null,
    completion_date timestamp(6) with time zone
);
