-- 동행 푸시 수신 대상과 비동기 발송 작업을 생성한다.
create table companion_push_endpoint
(
    id              bigint generated by default as identity primary key,
    user_id         bigint       not null,
    installation_id varchar(200) not null,
    token           varchar(4096) not null,
    platform        varchar(20)  not null,
    active          boolean      not null,
    last_seen_at    timestamp     not null,
    created_at      timestamp     not null,
    updated_at      timestamp     not null,
    constraint fk_companion_push_endpoint_user
        foreign key (user_id) references user_account (id),
    constraint uk_companion_push_endpoint_user_installation
        unique (user_id, installation_id)
);

create table companion_push_delivery
(
    id                   bigint generated by default as identity primary key,
    notification_id      bigint       not null,
    endpoint_id          bigint       not null,
    recipient_user_id    bigint       not null,
    token                varchar(4096) not null,
    title                varchar(100) not null,
    body                 text         not null,
    target_type          varchar(50)  not null,
    target_id            bigint       not null,
    status               varchar(30)  not null,
    attempt_count        integer      not null,
    next_attempt_at      timestamp    not null,
    lease_until          timestamp,
    claim_token          varchar(36),
    provider_message_id  varchar(255),
    last_error_code      varchar(255),
    expires_at           timestamp    not null,
    created_at           timestamp    not null,
    updated_at           timestamp    not null,
    constraint fk_companion_push_delivery_notification
        foreign key (notification_id) references companion_notification (id),
    constraint fk_companion_push_delivery_endpoint
        foreign key (endpoint_id) references companion_push_endpoint (id),
    constraint uk_companion_push_delivery_notification_endpoint
        unique (notification_id, endpoint_id)
);

create index idx_companion_push_endpoint_active_user
    on companion_push_endpoint (user_id, active, id);

create index idx_companion_push_delivery_due
    on companion_push_delivery (status, next_attempt_at, id);

create index idx_companion_push_delivery_expired_lease
    on companion_push_delivery (status, lease_until, id);

create index idx_companion_push_delivery_expiration
    on companion_push_delivery (status, expires_at, id);
