-- 동행 알림 읽음 상태 테이블을 생성한다.
create table companion_application_read_status
(
    id             bigint generated by default as identity primary key,
    application_id bigint    not null,
    user_id        bigint    not null,
    read_at        timestamp not null,
    constraint fk_companion_application_read_status_application
        foreign key (application_id) references companion_application (id),
    constraint uk_companion_application_read_status_application_user
        unique (application_id, user_id)
);
