-- 동행 알림 테이블을 생성한다.
create table companion_notification
(
    id                bigint generated by default as identity primary key,
    recipient_user_id bigint       not null,
    notification_type varchar(255) not null,
    target_type       varchar(255) not null,
    target_id         bigint       not null,
    read_at           timestamp,
    created_at        timestamp    not null,
    constraint uk_companion_notification_event_recipient
        unique (notification_type, target_type, target_id, recipient_user_id)
);
